package internal

import (
	"apps/apps/models"
)

type Repository interface {
	Save(generator *models.AutoGenerated, meta *models.Meta, data []*models.Data, pagination *models.Pagination, links *models.Links) error
}
