package internal

import (
	"task/models"
)

type UseCase interface {
	Save(generator *models.AutoGenerated, meta *models.Meta, data []*models.Data, pagination *models.Pagination, links *models.Links) error
}
