package usecase

import (
	"apps/apps/models"
	"apps/apps/parser/internal"
)

type Service struct {
	repository internal.Repository
}

func NewService(repository internal.Repository) *Service {
	return &Service{
		repository: repository,
	}
}

func (s *Service) Save(generator *models.AutoGenerated, meta *models.Meta, data []*models.Data, pagination *models.Pagination, links *models.Links) error {
	if err := s.repository.Save(generator, meta, data, pagination, links); err != nil {
		return err
	}
	return nil
}
